### ISSUE TITLE
Wander about how to debug this project in order to learn the paper in deep..

### ISSUE THREAD

**Issue by CodingCatMountain** [argmax-ai/constrained-promps#1]
Hi, Developers. I like the method you proposed in TRO paper "Constrained Probabilistic Movement Primitives for Robot Trajectory Adaptation". I think it really develop a new view about ProMPs. And I am glad you open this github repo to us. However, after I install this python package in my vmware and run the demo successfully, I wander about how to debug in order to learn about this method. So Could you give me some instructions? I will appreciate that! @felixfrank

**Comment by felixfrank** [comment]
Do you mean debug as in use a python debugger with the code?

You can start any of the scripts with `python -m pdb <script name>`. Look at [pdb](https://docs.python.org/3/library/pdb.html).
If you want something with a visual interface you can look at [debugpy](https://github.com/microsoft/debugpy) and vscode. Check out their documentation on how to start debugging python scripts. Be aware that you need to publish the correct port, ususally 5678, when starting the docker container. So add `-p 5678:5678` to the `docker.run` script.

**Comment by CodingCatMountain** [comment]
@felixfrank Thanks for reply!  Yeah, I usually like to learn a method via debugging the demo code. In past, I use ipdb package. So pdb is OK for me too. Do you mean that If I want to use ``python -m pdb <script name>``, I should firstly add ``-p 5678:5678`` to the ``docker.run``?

**Comment by felixfrank** [comment]
No, adding `-p 5678:5678` is only necessary if you want to use debugpy. There should be nothing stopping you from using `pdb` or `ipdb`. You just need to install `ipdb` in the docker container and start the script with `python -m ipdb ...`.

**Comment by CodingCatMountain** [comment]
@felixfrank Thank you very much! I will close this issue.

**Comment by felixfrank** [comment]
If you want to install `ipdb` in the docker container you need to remove the second line from the `docker.run` script.
https://github.com/argmax-ai/constrained-promps/blob/410a9158270838fe577c4d2f8864ffb446c7a780/docker.run#L2

This line changes your userid inside the docker container to be the same as your userid outside, which is necessary so you can access the results from the experiments outside of the docker container easily. However, it prevents you from installing any additional packages with pip. Simply remove the line and you can install packages in the running docker container.

**Comment by CodingCatMountain** [comment]
@felixfrank Thank you for this instruction! I am really a green hand for docker. :) 

> If you want to install `ipdb` in the docker container you need to remove the second line from the `docker.run` script.
> 
> https://github.com/argmax-ai/constrained-promps/blob/410a9158270838fe577c4d2f8864ffb446c7a780/docker.run#L2
> 
> This line changes your userid inside the docker container to be the same as your userid outside, which is necessary so you can access the results from the experiments outside of the docker container easily. However, it prevents you from installing any additional packages with pip. Simply remove the line and you can install packages in the running docker container.
